"""13th: create ReportOnUser model
+ relationships: (reporter)User:ReportOnUser(1:N) & (reported)User:ReportOnUser(1:N)

Revision ID: 1e5b92e6b7c4
Revises: 5fa112181c6d
Create Date: 2025-10-04 00:31:04.153670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5b92e6b7c4'
down_revision: Union[str, Sequence[str], None] = '5fa112181c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reports_on_users',
        sa.Column(
            'title',
            sa.Enum('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='user_report_title_choices_enum'),
            nullable=False
        ),
        sa.Column('reported_user_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('reporter_id', sa.BigInteger(), nullable=True),  # due to ondelete="SET NULL"
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['reported_user_id'],
            ['users.id'],
            name='fk_users_reports_for_reported_users',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['reporter_id'],
            ['users.id'],
            name='fk_users_reports_for_reporter',
            ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_reports_on_users_id'),
        'reports_on_users',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_reports_on_users_reported_user_id'),
        'reports_on_users',
        ['reported_user_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_on_users_reported_user_id'), table_name='reports_on_users')
    op.drop_index(op.f('ix_reports_on_users_id'), table_name='reports_on_users')
    op.drop_table('reports_on_users')
    # ### end Alembic commands ###
