"""7th: add some indexes (faster lookups)

Revision ID: 2b9fa5d3ddf1
Revises: 30fce99ec969
Create Date: 2025-09-29 13:17:23.554666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9fa5d3ddf1'
down_revision: Union[str, Sequence[str], None] = '30fce99ec969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_comments_comment_parent_id'),
        'comments',
        ['comment_parent_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_comments_post_parent_id'),
        'comments',
        ['post_parent_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_posts_user_id'),
        'posts',
        ['user_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_comments_post_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment_parent_id'), table_name='comments')
    # ### end Alembic commands ###
