"""6th: rebuild 'follows' table

Revision ID: 2e96bec383b5
Revises: fdd3e03521ee
Create Date: 2025-11-28 14:01:26.870389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e96bec383b5'
down_revision: Union[str, Sequence[str], None] = 'fdd3e03521ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('followed_by', sa.BigInteger(), nullable=False),
    sa.Column('followed', sa.BigInteger(), nullable=False),
    sa.Column('follow_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['followed'], ['users.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followed_by'], ['users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('followed_by', 'followed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
