"""11th: add saved_date column to saved_posts & user_saved_lists

Revision ID: 303d32209447
Revises: 66fa13a9235c
Create Date: 2025-10-03 20:14:06.005555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303d32209447'
down_revision: Union[str, Sequence[str], None] = '66fa13a9235c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'saved_posts',
        sa.Column(
            'saved_date',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )
    op.add_column(
        'user_saved_lists',
        sa.Column(
            'saved_date',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_saved_lists', 'saved_date')
    op.drop_column('saved_posts', 'saved_date')
    # ### end Alembic commands ###
