"""
6th: create Comment model + add relationships:
User:Comment 1:N - Post:Comment 1:N - Self Referenced for comments & replies

Revision ID: 30fce99ec969
Revises: d97970d0cd29
Create Date: 2025-09-29 12:50:16.229703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fce99ec969'
down_revision: Union[str, Sequence[str], None] = 'd97970d0cd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comments',
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('status', sa.Enum('PB', 'HD', 'DL', name='comment_status_enum'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('post_parent_id', sa.BigInteger(), nullable=True),
        sa.Column('comment_parent_id', sa.BigInteger(), nullable=True),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['comment_parent_id'],
            ['comments.id'],
            name='fk_comments_reply_comments',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['post_parent_id'],
            ['posts.id'],
            name='fk_posts_comments',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name='fk_users_comments',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
