"""14th: create ReportOnPost model
+ relationships: (reporter)User:ReportOnPost(1:N) & Post:ReportOnUser(1:N)

Revision ID: 3bf0d197dbb4
Revises: 1e5b92e6b7c4
Create Date: 2025-10-04 00:55:03.032753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf0d197dbb4'
down_revision: Union[str, Sequence[str], None] = '1e5b92e6b7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reports_on_posts',
        sa.Column(
            'title',
            sa.Enum('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='post_report_title_choices_enum'),
            nullable=False
        ),
        sa.Column('reported_post_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('reporter_id', sa.BigInteger(), nullable=True),  # due to ondelete="SET NULL"
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['reported_post_id'],
            ['posts.id'],
            name='fk_posts_reports',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['reporter_id'],
            ['users.id'],
            name='fk_users_reports_for_reporter',
            ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_reports_on_posts_id'),
        'reports_on_posts',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_reports_on_posts_reported_post_id'),
        'reports_on_posts',
        ['reported_post_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_on_posts_reported_post_id'), table_name='reports_on_posts')
    op.drop_index(op.f('ix_reports_on_posts_id'), table_name='reports_on_posts')
    op.drop_table('reports_on_posts')
    # ### end Alembic commands ###
