"""7th: del 'slug' field & index 'published_at' field in Post model

Revision ID: 46e28d035d44
Revises: 2e96bec383b5
Create Date: 2025-11-30 11:52:45.279074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e28d035d44'
down_revision: Union[str, Sequence[str], None] = '2e96bec383b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    # ### end Alembic commands ###
