"""12th: create Ticket model + User:Ticket(1:N) relationship

Revision ID: 5fa112181c6d
Revises: 303d32209447
Create Date: 2025-10-03 20:27:00.244198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa112181c6d'
down_revision: Union[str, Sequence[str], None] = '303d32209447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tickets',
        sa.Column('subject', sa.String(length=120), nullable=True),
        sa.Column('message', sa.String(length=4000), nullable=False),
        sa.Column('status', sa.Enum('N', 'R', 'C', name='ticket_status_enum'), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_tickets', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
