"""10th: create Profile & Link models + add related relationships

Revision ID: 66fa13a9235c
Revises: efe3b61c6ea9
Create Date: 2025-10-03 14:48:51.618537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fa13a9235c'
down_revision: Union[str, Sequence[str], None] = 'efe3b61c6ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiles',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('display_name', sa.String(length=64), nullable=True),
        sa.Column('about', sa.String(length=2000), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('gender', sa.Enum('MA', 'FM', 'OT', 'NS', name='profile_gender_enum'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profile_one2one', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(
        'idx_display_name_not_null',
        'profiles',
        ['display_name'],
        unique=False,
        postgresql_where='display_name IS NOT NULL'
    )

    op.create_table(
        'links',
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('profile_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.user_id'], name='fk_profile_links', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_profile_id'), 'links', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_profile_id'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_index('idx_display_name_not_null', table_name='profiles', postgresql_where='display_name IS NOT NULL')
    op.drop_table('profiles')
    # ### end Alembic commands ###
