"""9th: delete ticket and reports tables

Revision ID: 98771d1828af
Revises: bf105a2a2a76
Create Date: 2025-12-15 16:03:29.554500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98771d1828af'
down_revision: Union[str, Sequence[str], None] = 'bf105a2a2a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_index(op.f('ix_reports_on_users_reported_user_id'), table_name='reports_on_users')
    op.drop_table('reports_on_users')
    op.drop_index(op.f('ix_reports_on_posts_reported_post_id'), table_name='reports_on_posts')
    op.drop_table('reports_on_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_on_posts',
    sa.Column('title', postgresql.ENUM('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='post_report_title_choices_enum'), autoincrement=False, nullable=False),
    sa.Column('reported_post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ID', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('reporter_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reported_post_id'], ['posts.ID'], name=op.f('fk_posts_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.ID'], name=op.f('fk_users_reports_for_reporter'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID', name=op.f('reports_on_posts_pkey'))
    )
    op.create_index(op.f('ix_reports_on_posts_reported_post_id'), 'reports_on_posts', ['reported_post_id'], unique=False)
    op.create_table('reports_on_users',
    sa.Column('title', postgresql.ENUM('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='user_report_title_choices_enum'), autoincrement=False, nullable=False),
    sa.Column('reported_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ID', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('reporter_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.ID'], name=op.f('fk_users_reports_for_reported_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.ID'], name=op.f('fk_users_reports_for_reporter'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID', name=op.f('reports_on_users_pkey'))
    )
    op.create_index(op.f('ix_reports_on_users_reported_user_id'), 'reports_on_users', ['reported_user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('subject', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=4000), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('N', 'R', 'C', name='ticket_status_enum'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ID', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name=op.f('fk_users_tickets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID', name=op.f('tickets_pkey'))
    )
    # ### end Alembic commands ###
