"""reinitialization (recreate all tables again)

Revision ID: cac3d8999266
Revises: 
Create Date: 2025-10-05 01:10:43.557536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac3d8999266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)

    op.create_table(
        'users',
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table(
        'lists',
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('is_private', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name='fk_users_owned_lists', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_lists_user_id'), 'lists', ['user_id'], unique=False)

    op.create_table(
        'posts',
        sa.Column('title', sa.String(length=250), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('reading_time', sa.SmallInteger(), nullable=True),
        sa.Column('status', sa.Enum('DR', 'PB', 'RJ', 'DL', name='post_status_enum'), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name='fk_users_posts', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)

    op.create_table(
        'profiles',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('display_name', sa.String(length=64), nullable=True),
        sa.Column('about', sa.String(length=2000), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('gender', sa.Enum('MA', 'FM', 'OT', 'NS', name='profile_gender_enum'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name='user_profile_one2one', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_display_name_not_null', 'profiles', ['display_name'], unique=False, postgresql_where='display_name IS NOT NULL')

    op.create_table(
        'reports_on_users',
        sa.Column('title', sa.Enum('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='user_report_title_choices_enum'), nullable=False),
        sa.Column('reported_user_id', sa.BigInteger(), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('reporter_id', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['reported_user_id'], ['users.ID'], name='fk_users_reports_for_reported_users', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reporter_id'], ['users.ID'], name='fk_users_reports_for_reporter', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_reports_on_users_reported_user_id'), 'reports_on_users', ['reported_user_id'], unique=False)

    op.create_table(
        'tickets',
        sa.Column('subject', sa.String(length=120), nullable=True),
        sa.Column('message', sa.String(length=4000), nullable=False),
        sa.Column('status', sa.Enum('N', 'R', 'C', name='ticket_status_enum'), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name='fk_users_tickets', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('ID')
    )

    op.create_table(
        'comments',
        sa.Column('content', sa.String(length=1000), nullable=False),
        sa.Column('status', sa.Enum('PB', 'HD', 'DL', name='comment_status_enum'), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('post_parent_id', sa.BigInteger(), nullable=True),
        sa.Column('comment_parent_id', sa.BigInteger(), nullable=True),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['comment_parent_id'], ['comments.ID'], name='fk_comments_reply_comments', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_parent_id'], ['posts.ID'], name='fk_posts_comments', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], name='fk_users_comments', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_comments_comment_parent_id'), 'comments', ['comment_parent_id'], unique=False)
    op.create_index(op.f('ix_comments_post_parent_id'), 'comments', ['post_parent_id'], unique=False)

    op.create_table(
        'links',
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('profile_id', sa.BigInteger(), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.user_id'], name='fk_profile_links', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_links_profile_id'), 'links', ['profile_id'], unique=False)

    op.create_table(
        'posts_tags',
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.Column('tag_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.ID'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.ID'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('tag_id', 'post_id', name='posts_tags_composite_pk')
    )

    op.create_table(
        'reports_on_posts',
        sa.Column('title', sa.Enum('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'OT', name='post_report_title_choices_enum'), nullable=False),
        sa.Column('reported_post_id', sa.BigInteger(), nullable=False),
        sa.Column('ID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('reporter_id', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['reported_post_id'], ['posts.ID'], name='fk_posts_reports', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reporter_id'], ['users.ID'], name='fk_users_reports_for_reporter', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_reports_on_posts_reported_post_id'), 'reports_on_posts', ['reported_post_id'], unique=False)

    op.create_table(
        'saved_posts',
        sa.Column('list_id', sa.BigInteger(), nullable=False),
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.Column('saved_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['list_id'], ['lists.ID'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_id'], ['posts.ID'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('list_id', 'post_id', name='saved_posts_composite_pk')
    )

    op.create_table(
        'user_saved_lists',
        sa.Column('list_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('saved_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['list_id'], ['lists.ID'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.ID'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('list_id', 'user_id', name='user_saved_lists_composite_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_lists')
    op.drop_table('saved_posts')
    op.drop_index(op.f('ix_reports_on_posts_reported_post_id'), table_name='reports_on_posts')
    op.drop_table('reports_on_posts')
    op.drop_table('posts_tags')
    op.drop_index(op.f('ix_links_profile_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_comments_post_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment_parent_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_reports_on_users_reported_user_id'), table_name='reports_on_users')
    op.drop_table('reports_on_users')
    op.drop_index('idx_display_name_not_null', table_name='profiles', postgresql_where='display_name IS NOT NULL')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_lists_user_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
