"""4th: add 'is_private' column to Post Model

Revision ID: cdb92bee78df
Revises: 32fe0787e6e7
Create Date: 2025-10-08 12:31:56.506737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb92bee78df'
down_revision: Union[str, Sequence[str], None] = '32fe0787e6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column(
            'is_private', sa.Boolean(), nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_private')
    # ### end Alembic commands ###
