"""
2nd: add M2M relationship: User:User (follow system)
via 'follows' association table

Revision ID: d2283d616e4a
Revises: cac3d8999266
Create Date: 2025-10-05 11:58:11.153046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2283d616e4a'
down_revision: Union[str, Sequence[str], None] = 'cac3d8999266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('following_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
