"""5th: few chages in 'follows' table

Revision ID: dd71b8e970af
Revises: cdb92bee78df
Create Date: 2025-11-28 13:38:09.319765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd71b8e970af'
down_revision: Union[str, Sequence[str], None] = 'cdb92bee78df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('followed_by', sa.BigInteger(), nullable=False))
    op.add_column('follows', sa.Column('followed', sa.BigInteger(), nullable=False))
    op.add_column('follows', sa.Column('follow_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('follows_follower_id_fkey'), 'follows', type_='foreignkey')
    op.drop_constraint(op.f('follows_following_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed'], ['ID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follows', 'users', ['followed_by'], ['ID'], ondelete='CASCADE')
    op.drop_column('follows', 'follower_id')
    op.drop_column('follows', 'followed_at')
    op.drop_column('follows', 'following_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('following_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('followed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('follows', sa.Column('follower_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_following_id_fkey'), 'follows', 'users', ['following_id'], ['ID'], ondelete='CASCADE')
    op.create_foreign_key(op.f('follows_follower_id_fkey'), 'follows', 'users', ['follower_id'], ['ID'], ondelete='CASCADE')
    op.drop_column('follows', 'follow_at')
    op.drop_column('follows', 'followed')
    op.drop_column('follows', 'followed_by')
    # ### end Alembic commands ###
