"""5th: delete 'follows' table

Revision ID: fdd3e03521ee
Revises: dd71b8e970af
Create Date: 2025-11-28 13:51:52.962566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdd3e03521ee'
down_revision: Union[str, Sequence[str], None] = 'dd71b8e970af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('followed_by', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('followed', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('follow_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed'], ['users.ID'], name=op.f('follows_followed_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followed_by'], ['users.ID'], name=op.f('follows_followed_by_fkey'), ondelete='CASCADE')
    )
    # ### end Alembic commands ###
